package com.bigoviw887.modulo.schema;

import com.bigoviw887.modulo.model.TaskImportance;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonProperty.Access;
import javax.annotation.processing.Generated;
import lombok.AllArgsConstructor;
import lombok.Getter;
import lombok.NoArgsConstructor;
import lombok.Setter;

@Generated(value = "com.exocoding.codegen", comments = "Generated by ExoCoding 0.0.1-SNAPSHOT")
@Getter
@Setter
@AllArgsConstructor
@NoArgsConstructor
public class TaskHdrSchema {

  @JsonProperty(access = Access.READ_ONLY)
  protected Long id;

  protected Integer tp;

  protected Integer nr;

  protected String name;

  protected TaskImportance importance;
}
