package com.bigoviw887.modulo.schema;

import javax.annotation.processing.Generated;
import lombok.AllArgsConstructor;
import lombok.Getter;
import lombok.NoArgsConstructor;
import lombok.Setter;

/** Object of entity of User */
@Generated(value = "com.exocoding.codegen", comments = "Generated by ExoCoding 0.0.1-SNAPSHOT")
@Getter
@Setter
@AllArgsConstructor
@NoArgsConstructor
public class UserObjSchema {

  // idUser
  protected Long idUser;

  // name
  protected String name;

  // username
  protected String username;

  // email
  protected String email;
}
