
/**
 * Generated by ExoCoding 0.0.1
 */


/**
 * Importance of task
 */
export enum TaskImportance {
// Important
    IMPORTANT = 1,
// Normal
    NORMAL = 0,
// Unimportant
    UNIMPORTANT = -1,
}

export type TaskHdr = {
    id: number;
    tp: number;
    nr: number;
    name: string;
    importance: any;
}

export type dsfsdf = {
}

/**
 * Object of endpoint \account
 */
export type Account = {
    // userObj
    user: UserObj;
    // roles
    roles: string[];
}

/**
 * To preform the register
 */
export type UserRegister = {
    // username
    username: string;
    // password
    password: string;
    // name
    name: string;
    // email
    email: string;
}

/**
 * To preform the login
 */
export type UserLogin = {
    // email
    email: string;
    // password
    password: string;
}

/**
 * Object of entity of User
 */
export type UserObj = {
    // idUser
    idUser: number;
    // name
    name: string;
    // username
    username: string;
    // email
    email: string;
}
