
/**
 * Generated by ExoCoding 0.0.1
 */


/**
 * Object of entity of Assets
 */
export type AssetsObj = {
    // assetId
    assetId: number;
    // name
    name: string;
    // extension
    extension: string;
    // mimetype
    mimetype: string;
    // checksum
    checksum: string;
    // blob
    blob: FileList | null;
    // size
    size: number;
}
