package com.bigoviw887.modulo.mapper;

import com.bigoviw887.modulo.dto.AssetsObjDto;
import com.bigoviw887.modulo.model.Assets;
import com.bigoviw887.modulo.schema.AssetsObjSchema;
import java.util.List;
import javax.annotation.processing.Generated;
import org.mapstruct.BeanMapping;
import org.mapstruct.Mapper;
import org.mapstruct.MappingTarget;
import org.mapstruct.NullValuePropertyMappingStrategy;
import org.springframework.stereotype.Component;

@Generated(value = "com.exocoding.codegen", comments = "Generated by ExoCoding 0.0.1-SNAPSHOT")
@Component
@Mapper
public interface AssetsObjMapper {

  Assets dtoToEntity(AssetsObjDto dto);

  List<Assets> dtoToEntity(List<AssetsObjDto> dtoList);

  AssetsObjSchema dtoToSchema(AssetsObjDto dto);

  List<AssetsObjSchema> dtoToSchema(List<AssetsObjDto> dtoList);

  AssetsObjDto entityToDto(Assets entity);

  List<AssetsObjDto> entityToDto(List<Assets> entityList);

  AssetsObjDto schemaToDto(AssetsObjSchema schema);

  List<AssetsObjDto> schemaToDto(List<AssetsObjSchema> schemaList);

  @BeanMapping(nullValuePropertyMappingStrategy = NullValuePropertyMappingStrategy.IGNORE)
  void updateFromDto(@MappingTarget Assets entity, AssetsObjDto dto);
}
