package com.bigoviw887.modulo.mapper;

import com.bigoviw887.modulo.dto.AssetsObjDto;
import com.bigoviw887.modulo.model.Assets;
import java.util.List;
import javax.annotation.processing.Generated;
import org.mapstruct.BeanMapping;
import org.mapstruct.Mapper;
import org.mapstruct.MappingTarget;
import org.mapstruct.NullValuePropertyMappingStrategy;
import org.springframework.stereotype.Component;

@Generated(value = "com.exocoding.codegen", comments = "Generated by ExoCoding 0.0.1-SNAPSHOT")
@Component
@Mapper
public abstract class AssetsObjWriteMapper extends EntityMapper {

  public abstract Assets dtoToEntity(AssetsObjDto dto);

  public abstract List<Assets> dtoToEntity(List<AssetsObjDto> dtoList);

  public abstract AssetsObjDto entityToDto(Assets entity);

  public abstract List<AssetsObjDto> entityToDto(List<Assets> entityList);

  @BeanMapping(nullValuePropertyMappingStrategy = NullValuePropertyMappingStrategy.IGNORE)
  public abstract void updateFromDto(@MappingTarget Assets entity, AssetsObjDto dto);
}
