package com.bigoviw887.modulo.model;

import jakarta.persistence.Column;
import jakarta.persistence.Entity;
import jakarta.persistence.GeneratedValue;
import jakarta.persistence.GenerationType;
import jakarta.persistence.Id;
import jakarta.persistence.Table;
import java.math.BigDecimal;
import javax.annotation.processing.Generated;
import lombok.Data;

/** Products */
@Generated(value = "com.exocoding.codegen", comments = "Generated by ExoCoding 0.0.1-SNAPSHOT")
@Data
@Entity
@Table
public class Products extends AbstractEntity {

  @Column(name = "product_id", nullable = false)
  @Id
  @GeneratedValue(strategy = GenerationType.IDENTITY)
  protected Long productId;

  @Column(name = "product_name", nullable = false, columnDefinition = "text")
  protected String productName;

  @Column(nullable = false)
  protected BigDecimal price;
}
