package com.bigoviw887.modulo.model;

import jakarta.persistence.Column;
import jakarta.persistence.Entity;
import jakarta.persistence.GeneratedValue;
import jakarta.persistence.GenerationType;
import jakarta.persistence.Id;
import jakarta.persistence.Table;
import javax.annotation.processing.Generated;
import lombok.Data;

/** Users */
@Generated(value = "com.exocoding.codegen", comments = "Generated by ExoCoding 0.0.1-SNAPSHOT")
@Data
@Entity
@Table
public class Users extends AbstractEntity {

  @Column(name = "user_id", nullable = false)
  @Id
  @GeneratedValue(strategy = GenerationType.IDENTITY)
  protected Long userId;

  @Column(nullable = false, columnDefinition = "text")
  protected String username;

  @Column(nullable = false, columnDefinition = "text")
  protected String email;
}
