
/**
 * Generated by ExoCoding 0.0.1
 */

import { AxiosRequestConfig } from 'axios';
import { axios } from '@/lib/axios';
import { Page } from '@/types';
import { Account } from '@/modules/authentication/types';
import { UserLoginDTO } from '.';
import { UserRegisterDTO } from '.';

/**
 * 
*
* @param {body} userSignup
* @param {options} Override http request option.
* @returns Register OK */
export const signup = (body: UserRegisterDTO, options: AxiosRequestConfig = {}): Promise<any> => {
    return axios.post(`/signup`, body, options);
};

/**
 * 
*
* @param {options} Override http request option.
* @returns recover OK */
export const account = (options: AxiosRequestConfig = {}): Promise<Account> => {
    return axios.get(`/account`, options);
};

/**
 * 
*
* @param {options} Override http request option.
* @returns Logout OK */
export const logout = (options: AxiosRequestConfig = {}): Promise<any> => {
    return axios.delete(`/logout`, options);
};

/**
 * 
*
* @param {body} userLogin
* @param {options} Override http request option.
* @returns Login OK */
export const login = (body: UserLoginDTO, options: AxiosRequestConfig = {}): Promise<Account> => {
    return axios.post(`/login`, body, options);
};
