
/**
 * Generated by ExoCoding 0.0.1
 */

import { AxiosRequestConfig } from 'axios';
import { axios } from '@/lib/axios';
import { Page } from '@/types';
import { AssetsObj } from '@/modules/storage/types';
import { AssetsObjDTO } from '.';

/**
 * 
*
* @param {body} file
* @param {options} Override http request option. */
export const uploadAssets = (body: AssetsObjDTO, options: AxiosRequestConfig = {}): Promise<any> => {
    var formData = new FormData();
    if (body.blob) formData.append("file", body.blob[0]);
    return axios.post(`/assets`, formData, options);
};

/**
 * 
*
* @param {id} assetsId
* @param {options} Override http request option.
* @returns Asset found */
export const assets = (id:  number, options: AxiosRequestConfig = {}): Promise<AssetsObj> => {
    return axios.get(`/assets/${id}`, options);
};

/**
 * 
*
* @param {id} assetsId
* @param {options} Override http request option.
* @returns Asset deleted */
export const deleteAssets = (id:  number, options: AxiosRequestConfig = {}): Promise<AssetsObj> => {
    return axios.delete(`/assets/${id}`, options);
};
