package com.bigoviw887.modulo.model;

import javax.annotation.processing.Generated;

/** Abstract class common to all entities. */
@Generated(value = "com.exocoding.codegen", comments = "Generated by ExoCoding 0.0.1-SNAPSHOT")
public abstract class AbstractEntity {}
