package com.bigoviw887.modulo.model;

import jakarta.persistence.Column;
import jakarta.persistence.Entity;
import jakarta.persistence.FetchType;
import jakarta.persistence.GeneratedValue;
import jakarta.persistence.GenerationType;
import jakarta.persistence.Id;
import jakarta.persistence.OneToMany;
import jakarta.persistence.Table;
import java.util.LinkedList;
import java.util.List;
import javax.annotation.processing.Generated;
import lombok.Data;
import org.springframework.security.core.GrantedAuthority;

/** ... */
@Generated(value = "com.exocoding.codegen", comments = "Generated by ExoCoding 0.0.1-SNAPSHOT")
@Data
@Entity
@Table
public class Permission extends AbstractEntity implements GrantedAuthority {

  @Column(nullable = false)
  @Id
  @GeneratedValue(strategy = GenerationType.IDENTITY)
  protected Long idPermission;

  // relationship between permission and RolePermission
  @OneToMany(mappedBy = "permission", fetch = FetchType.LAZY, orphanRemoval = true)
  protected List<RolePermission> rolePermission = new LinkedList<>();

  @Column(nullable = false)
  protected String name;

  public void addRolePermission(RolePermission rolePermission) {
    this.rolePermission.add(rolePermission);
    rolePermission.setPermission(this);
  }

  public void removeRolePermission(RolePermission rolePermission) {
    this.rolePermission.remove(rolePermission);
    rolePermission.setPermission(null);
  }

  public void setRolePermission(List<RolePermission> rolePermission) {
    if (this.rolePermission != null) {
      this.rolePermission.forEach(z -> z.setPermission(null));
    }
    if (rolePermission != null) {
      rolePermission.forEach(z -> z.setPermission(this));
    }
    this.rolePermission = rolePermission;
  }

  @Override
  public String getAuthority() {
    return this.getName();
  }
}
