package com.bigoviw887.modulo.model;

import jakarta.persistence.Column;
import jakarta.persistence.Entity;
import jakarta.persistence.FetchType;
import jakarta.persistence.GeneratedValue;
import jakarta.persistence.GenerationType;
import jakarta.persistence.Id;
import jakarta.persistence.JoinColumn;
import jakarta.persistence.ManyToOne;
import jakarta.persistence.Table;
import javax.annotation.processing.Generated;
import lombok.Data;

/** ... */
@Generated(value = "com.exocoding.codegen", comments = "Generated by ExoCoding 0.0.1-SNAPSHOT")
@Data
@Entity
@Table
public class RolePermission extends AbstractEntity {

  @Column(nullable = false)
  @Id
  @GeneratedValue(strategy = GenerationType.IDENTITY)
  protected Long idRolePermission;

  // relationship between role and RolePermission
  @ManyToOne(fetch = FetchType.LAZY)
  @JoinColumn(name = "idRole_FK", referencedColumnName = "idRole", nullable = false)
  protected Role role;

  // relationship between permission and RolePermission
  @ManyToOne(fetch = FetchType.LAZY)
  @JoinColumn(name = "idPermission_FK", referencedColumnName = "idPermission", nullable = false)
  protected Permission permission;
}
