package com.bigoviw887.modulo.model;

import jakarta.persistence.AttributeConverter;
import jakarta.persistence.Converter;
import javax.annotation.processing.Generated;

/** Converts an TaskImportance to its value and vice-versa. */
@Generated(value = "com.exocoding.codegen", comments = "Generated by ExoCoding 0.0.1-SNAPSHOT")
@Converter(autoApply = true)
public class TaskImportanceConverter implements AttributeConverter<TaskImportance, Integer> {

  @Override
  public Integer convertToDatabaseColumn(TaskImportance attribute) {
    if (attribute == null) {
      return null;
    }
    return attribute.getValue();
  }

  @Override
  public TaskImportance convertToEntityAttribute(Integer dbData) {
    if (dbData == null) {
      return null;
    }
    return TaskImportance.of(dbData);
  }
}
