package com.bigoviw887.modulo.model;

import javax.annotation.processing.Generated;
import lombok.Getter;

/** Importance of task */
@Generated(value = "com.exocoding.codegen", comments = "Generated by ExoCoding 0.0.1-SNAPSHOT")
public enum TaskImportance {

  // Unimportant
  UNIMPORTANT(-1),

  // Normal
  NORMAL(0),

  // Important
  IMPORTANT(1);

  TaskImportance(int value) {
    this.value = value;
  }

  @Getter private final int value;

  public static TaskImportance of(int value) {
    for (TaskImportance v : values()) {
      if (v.value == value) {
        return v;
      }
    }
    return null;
  }
}
