package com.bigoviw887.modulo.model;

import jakarta.persistence.Column;
import jakarta.persistence.Entity;
import jakarta.persistence.FetchType;
import jakarta.persistence.GeneratedValue;
import jakarta.persistence.GenerationType;
import jakarta.persistence.Id;
import jakarta.persistence.Index;
import jakarta.persistence.JoinColumn;
import jakarta.persistence.ManyToOne;
import jakarta.persistence.Table;
import jakarta.persistence.UniqueConstraint;
import javax.annotation.processing.Generated;
import lombok.Data;

/** Task Header */
@Generated(value = "com.exocoding.codegen", comments = "Generated by ExoCoding 0.0.1-SNAPSHOT")
@Data
@Entity
@Table(
    indexes = {@Index(name = "type_nr", columnList = "tp DESC, nr ASC")},
    uniqueConstraints = {@UniqueConstraint(columnNames = {"tp", "nr"})})
public class TaskHdr extends AbstractEntity {

  @Column(nullable = false)
  @Id
  @GeneratedValue(strategy = GenerationType.IDENTITY)
  protected Long id;

  // Parent task
  @ManyToOne(fetch = FetchType.LAZY)
  @JoinColumn(name = "id", nullable = false)
  protected TaskDet taskHdr;

  @Column(nullable = false)
  protected TaskImportance importance;

  @Column(nullable = false)
  protected Integer tp;

  @Column(nullable = false)
  protected String name;

  @Column(nullable = false)
  protected Integer nr;
}
