package com.bigoviw887.modulo.model;

import jakarta.persistence.CascadeType;
import jakarta.persistence.Column;
import jakarta.persistence.Entity;
import jakarta.persistence.FetchType;
import jakarta.persistence.GeneratedValue;
import jakarta.persistence.GenerationType;
import jakarta.persistence.Id;
import jakarta.persistence.JoinColumn;
import jakarta.persistence.ManyToOne;
import jakarta.persistence.Table;
import javax.annotation.processing.Generated;
import lombok.Data;

/** ... */
@Generated(value = "com.exocoding.codegen", comments = "Generated by ExoCoding 0.0.1-SNAPSHOT")
@Data
@Entity
@Table
public class UserRole extends AbstractEntity {

  @Column(nullable = false)
  @Id
  @GeneratedValue(strategy = GenerationType.IDENTITY)
  protected Long idUserRole;

  // relationship between user and UserRole
  @ManyToOne(
      cascade = {CascadeType.PERSIST},
      fetch = FetchType.LAZY)
  @JoinColumn(name = "idUser_FK", referencedColumnName = "idUser", nullable = false)
  protected User user;

  // relationship between role and UserRole
  @ManyToOne(
      cascade = {CascadeType.PERSIST},
      fetch = FetchType.LAZY)
  @JoinColumn(name = "idRole_FK", referencedColumnName = "idRole", nullable = false)
  protected Role role;
}
