package com.bigoviw887.modulo.model;

import jakarta.persistence.Column;
import jakarta.persistence.Entity;
import jakarta.persistence.GeneratedValue;
import jakarta.persistence.GenerationType;
import jakarta.persistence.Id;
import jakarta.persistence.Lob;
import jakarta.persistence.Table;
import javax.annotation.processing.Generated;
import lombok.Data;

/** Assets Description */
@Generated(value = "com.exocoding.codegen", comments = "Generated by ExoCoding 0.0.1-SNAPSHOT")
@Data
@Entity
@Table
public class Assets extends AbstractEntity {

  @Column(nullable = false)
  @Id
  @GeneratedValue(strategy = GenerationType.IDENTITY)
  protected Long assetId;

  @Column(nullable = false, columnDefinition = "text")
  protected String checksum;

  @Column(name = "\"blob\"", nullable = false)
  @Lob
  protected byte[] blob;

  @Column(nullable = false, columnDefinition = "text")
  protected String mimetype;

  @Column(name = "\"size\"", nullable = false)
  protected Integer size;

  @Column(nullable = false, columnDefinition = "text")
  protected String extension;

  @Column(nullable = false, columnDefinition = "text")
  protected String name;
}
