package com.bigoviw887.modulo.mapper;

import com.bigoviw887.modulo.dto.DsfsdfDto;
import com.bigoviw887.modulo.schema.DsfsdfSchema;
import java.util.List;
import javax.annotation.processing.Generated;
import org.mapstruct.Mapper;
import org.mapstruct.Mapping;
import org.springframework.stereotype.Component;

@Generated(value = "com.exocoding.codegen", comments = "Generated by ExoCoding 0.0.1-SNAPSHOT")
@Component
@Mapper
public interface DsfsdfMapper {

  DsfsdfSchema dtoToSchema(DsfsdfDto dto);

  List<DsfsdfSchema> dtoToSchema(List<DsfsdfDto> dtoList);

  @Mapping(target = "field1", ignore = true)
  DsfsdfDto schemaToDto(DsfsdfSchema schema);

  List<DsfsdfDto> schemaToDto(List<DsfsdfSchema> schemaList);
}
