package com.bigoviw887.modulo.mapper;

import com.bigoviw887.modulo.dto.TaskHdrDto;
import com.bigoviw887.modulo.model.TaskHdr;
import com.bigoviw887.modulo.schema.TaskHdrSchema;
import java.util.List;
import javax.annotation.processing.Generated;
import org.mapstruct.BeanMapping;
import org.mapstruct.Mapper;
import org.mapstruct.MappingTarget;
import org.mapstruct.NullValuePropertyMappingStrategy;
import org.springframework.stereotype.Component;

@Generated(value = "com.exocoding.codegen", comments = "Generated by ExoCoding 0.0.1-SNAPSHOT")
@Component
@Mapper
public interface TaskHdrMapper {

  TaskHdr dtoToEntity(TaskHdrDto dto);

  List<TaskHdr> dtoToEntity(List<TaskHdrDto> dtoList);

  TaskHdrSchema dtoToSchema(TaskHdrDto dto);

  List<TaskHdrSchema> dtoToSchema(List<TaskHdrDto> dtoList);

  TaskHdrDto entityToDto(TaskHdr entity);

  List<TaskHdrDto> entityToDto(List<TaskHdr> entityList);

  TaskHdrDto schemaToDto(TaskHdrSchema schema);

  List<TaskHdrDto> schemaToDto(List<TaskHdrSchema> schemaList);

  @BeanMapping(nullValuePropertyMappingStrategy = NullValuePropertyMappingStrategy.IGNORE)
  void updateFromDto(@MappingTarget TaskHdr entity, TaskHdrDto dto);
}
