package com.bigoviw887.modulo.mapper;

import com.bigoviw887.modulo.dto.TaskHdrDto;
import com.bigoviw887.modulo.model.TaskHdr;
import java.util.List;
import javax.annotation.processing.Generated;
import org.mapstruct.BeanMapping;
import org.mapstruct.Mapper;
import org.mapstruct.MappingTarget;
import org.mapstruct.NullValuePropertyMappingStrategy;
import org.springframework.stereotype.Component;

@Generated(value = "com.exocoding.codegen", comments = "Generated by ExoCoding 0.0.1-SNAPSHOT")
@Component
@Mapper
public abstract class TaskHdrWriteMapper extends EntityMapper {

  public abstract TaskHdr dtoToEntity(TaskHdrDto dto);

  public abstract List<TaskHdr> dtoToEntity(List<TaskHdrDto> dtoList);

  public abstract TaskHdrDto entityToDto(TaskHdr entity);

  public abstract List<TaskHdrDto> entityToDto(List<TaskHdr> entityList);

  @BeanMapping(nullValuePropertyMappingStrategy = NullValuePropertyMappingStrategy.IGNORE)
  public abstract void updateFromDto(@MappingTarget TaskHdr entity, TaskHdrDto dto);
}
