package com.bigoviw887.modulo.mapper;

import com.bigoviw887.modulo.dto.TaskHdrDto;
import com.bigoviw887.modulo.model.TaskHdr;
import java.util.List;
import javax.annotation.processing.Generated;
import org.mapstruct.Mapper;
import org.springframework.stereotype.Component;

@Generated(value = "com.exocoding.codegen", comments = "Generated by ExoCoding 0.0.1-SNAPSHOT")
@Component
@Mapper
public abstract class TaskHdrReadMapper extends EntityMapper {

  public abstract TaskHdrDto entityToDto(TaskHdr entity);

  public abstract List<TaskHdrDto> entityToDto(List<TaskHdr> entityList);
}
