package com.bigoviw887.modulo.mapper;

import com.bigoviw887.modulo.dto.UserObjDto;
import com.bigoviw887.modulo.model.User;
import com.bigoviw887.modulo.schema.UserObjSchema;
import java.util.List;
import javax.annotation.processing.Generated;
import org.mapstruct.BeanMapping;
import org.mapstruct.Mapper;
import org.mapstruct.Mapping;
import org.mapstruct.MappingTarget;
import org.mapstruct.NullValuePropertyMappingStrategy;
import org.springframework.stereotype.Component;

@Generated(value = "com.exocoding.codegen", comments = "Generated by ExoCoding 0.0.1-SNAPSHOT")
@Component
@Mapper
public interface UserObjMapper {

  User dtoToEntity(UserObjDto dto);

  List<User> dtoToEntity(List<UserObjDto> dtoList);

  UserObjSchema dtoToSchema(UserObjDto dto);

  List<UserObjSchema> dtoToSchema(List<UserObjDto> dtoList);

  UserObjDto entityToDto(User entity);

  List<UserObjDto> entityToDto(List<User> entityList);

  @Mapping(target = "password", ignore = true)
  UserObjDto schemaToDto(UserObjSchema schema);

  List<UserObjDto> schemaToDto(List<UserObjSchema> schemaList);

  @BeanMapping(nullValuePropertyMappingStrategy = NullValuePropertyMappingStrategy.IGNORE)
  void updateFromDto(@MappingTarget User entity, UserObjDto dto);
}
