package com.bigoviw887.modulo.mapper;

import com.bigoviw887.modulo.dto.UserObjDto;
import com.bigoviw887.modulo.model.User;
import java.util.List;
import javax.annotation.processing.Generated;
import org.mapstruct.Mapper;
import org.springframework.stereotype.Component;

@Generated(value = "com.exocoding.codegen", comments = "Generated by ExoCoding 0.0.1-SNAPSHOT")
@Component
@Mapper
public abstract class UserObjReadMapper extends EntityMapper {

  public abstract UserObjDto entityToDto(User entity);

  public abstract List<UserObjDto> entityToDto(List<User> entityList);
}
