package com.bigoviw887.modulo.mapper;

import com.bigoviw887.modulo.dto.UserLoginDto;
import com.bigoviw887.modulo.schema.UserLoginSchema;
import java.util.List;
import javax.annotation.processing.Generated;
import org.mapstruct.Mapper;
import org.springframework.stereotype.Component;

@Generated(value = "com.exocoding.codegen", comments = "Generated by ExoCoding 0.0.1-SNAPSHOT")
@Component
@Mapper
public interface UserLoginMapper {

  UserLoginSchema dtoToSchema(UserLoginDto dto);

  List<UserLoginSchema> dtoToSchema(List<UserLoginDto> dtoList);

  UserLoginDto schemaToDto(UserLoginSchema schema);

  List<UserLoginDto> schemaToDto(List<UserLoginSchema> schemaList);
}
