package com.bigoviw887.modulo.mapper;

import com.bigoviw887.modulo.dto.UserObjDto;
import com.bigoviw887.modulo.model.User;
import java.util.List;
import javax.annotation.processing.Generated;
import org.mapstruct.BeanMapping;
import org.mapstruct.Mapper;
import org.mapstruct.MappingTarget;
import org.mapstruct.NullValuePropertyMappingStrategy;
import org.springframework.stereotype.Component;

@Generated(value = "com.exocoding.codegen", comments = "Generated by ExoCoding 0.0.1-SNAPSHOT")
@Component
@Mapper
public abstract class UserObjWriteMapper extends EntityMapper {

  public abstract User dtoToEntity(UserObjDto dto);

  public abstract List<User> dtoToEntity(List<UserObjDto> dtoList);

  public abstract UserObjDto entityToDto(User entity);

  public abstract List<UserObjDto> entityToDto(List<User> entityList);

  @BeanMapping(nullValuePropertyMappingStrategy = NullValuePropertyMappingStrategy.IGNORE)
  public abstract void updateFromDto(@MappingTarget User entity, UserObjDto dto);
}
