package com.bigoviw887.modulo.mapper;

import com.bigoviw887.modulo.dto.UserRegisterDto;
import com.bigoviw887.modulo.schema.UserRegisterSchema;
import java.util.List;
import javax.annotation.processing.Generated;
import org.mapstruct.Mapper;
import org.springframework.stereotype.Component;

@Generated(value = "com.exocoding.codegen", comments = "Generated by ExoCoding 0.0.1-SNAPSHOT")
@Component
@Mapper
public interface UserRegisterMapper {

  UserRegisterSchema dtoToSchema(UserRegisterDto dto);

  List<UserRegisterSchema> dtoToSchema(List<UserRegisterDto> dtoList);

  UserRegisterDto schemaToDto(UserRegisterSchema schema);

  List<UserRegisterDto> schemaToDto(List<UserRegisterSchema> schemaList);
}
