package com.bigoviw887.modulo.dto;

import javax.annotation.processing.Generated;
import lombok.AllArgsConstructor;
import lombok.EqualsAndHashCode;
import lombok.Getter;
import lombok.NoArgsConstructor;
import lombok.Setter;

/** Object of entity of Assets */
@Generated(value = "com.exocoding.codegen", comments = "Generated by ExoCoding 0.0.1-SNAPSHOT")
@Getter
@Setter
@AllArgsConstructor
@NoArgsConstructor
@EqualsAndHashCode(onlyExplicitlyIncluded = true)
public class AssetsObjDto {

  // assetId
  @EqualsAndHashCode.Include protected Integer assetId;

  // name
  protected String name;

  // extension
  protected String extension;

  // mimetype
  protected String mimetype;

  // checksum
  protected String checksum;

  // blob
  protected byte[] blob;

  // size
  protected Integer size;
}
