package com.bigoviw887.modulo.schema;

import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonProperty.Access;
import javax.annotation.processing.Generated;
import lombok.AllArgsConstructor;
import lombok.Getter;
import lombok.Setter;

/** Object of entity of Assets */
@Generated(value = "com.exocoding.codegen", comments = "Generated by ExoCoding 0.0.1-SNAPSHOT")
@Getter
@Setter
@AllArgsConstructor
public class AssetsObjSchema {

  // assetId
  @JsonProperty(access = Access.READ_ONLY)
  protected Integer assetId;

  // name
  @JsonProperty(access = Access.READ_ONLY)
  protected String name;

  // extension
  @JsonProperty(access = Access.READ_ONLY)
  protected String extension;

  // mimetype
  @JsonProperty(access = Access.READ_ONLY)
  protected String mimetype;

  // checksum
  @JsonProperty(access = Access.READ_ONLY)
  protected String checksum;

  // blob
  protected byte[] blob;

  // size
  @JsonProperty(access = Access.READ_ONLY)
  protected Integer size;
}
