package com.bigoviw887.modulo.repos;

import com.bigoviw887.modulo.model.RolePermission;
import java.util.List;
import javax.annotation.processing.Generated;
import org.springframework.data.jpa.repository.JpaRepository;
import org.springframework.data.jpa.repository.JpaSpecificationExecutor;
import org.springframework.stereotype.Repository;

@Generated(value = "com.exocoding.codegen", comments = "Generated by ExoCoding 0.0.1-SNAPSHOT")
@Repository
public interface RolePermissionRepository
    extends JpaRepository<RolePermission, Long>, JpaSpecificationExecutor<RolePermission> {

  void deleteByPermission(Long idPermissionFk);

  void deleteByRole(Long idRoleFk);

  List<RolePermission> findByPermission(Long idPermissionFk);

  List<RolePermission> findByRole(Long idRoleFk);
}
