package com.bigoviw887.modulo.repos;

import com.bigoviw887.modulo.model.TaskHdr;
import java.util.List;
import javax.annotation.processing.Generated;
import org.springframework.data.jpa.repository.JpaRepository;
import org.springframework.data.jpa.repository.JpaSpecificationExecutor;
import org.springframework.stereotype.Repository;

@Generated(value = "com.exocoding.codegen", comments = "Generated by ExoCoding 0.0.1-SNAPSHOT")
@Repository
public interface TaskHdrRepository
    extends JpaRepository<TaskHdr, Long>, JpaSpecificationExecutor<TaskHdr> {

  void deleteByTaskHdr(Long id);

  List<TaskHdr> findByTaskHdr(Long id);
}
