
/**
 * Generated by ExoCoding 0.0.1
 */

import * as React from 'react';
import SessionContext, { SessionContextType } from '@/modules/authentication/session';
import { account } from '@/modules/authentication/api';

/**
 * Class responsible for requesting session details
 */
const useSession = (): [boolean, SessionContextType] => {
  const session = React.useContext(SessionContext);
  const [loading, setLoading] = React.useState(true);

  React.useEffect(() => {
    if (!session.isLoggedIn) {
      fetchAccount();
    } else {
      setLoading(false);
    }
  }, [session]);

  async function fetchAccount() {
    try {
      const accountRes = await account();
      session.setAccount(accountRes);
      session.setLoggedIn(true);
      setLoading(false);
    } catch (e) {
      session.setLoggedIn(false);
      session.setAccount(null);
      setLoading(false);
    }
  }

  return [loading, session];
};

export default useSession;
