
/**
 * Generated by ExoCoding 0.0.1
 */

import React from 'react';
import { Account } from '@/modules/authentication/types';

/**
 * Class responsible for create context of session
 */
export type SessionContextType = {
    isLoggedIn: boolean;
    setLoggedIn: (value: boolean) => void;
    account: Account | null;
    setAccount: (user: Account | null) => void;
    logout: () => Promise<void>;
}

const initialState: SessionContextType = {
    isLoggedIn: false,
    setLoggedIn: () => {},
    account: null,
    setAccount: () => {},
    logout: async () => {}
}

const SessionContext = React.createContext<SessionContextType>(initialState);

export default SessionContext;
