package com.bigoviw887.modulo.repos;

import com.bigoviw887.modulo.model.OrderItems;
import java.util.List;
import javax.annotation.processing.Generated;
import org.springframework.data.jpa.repository.JpaRepository;
import org.springframework.data.jpa.repository.JpaSpecificationExecutor;
import org.springframework.stereotype.Repository;

@Generated(value = "com.exocoding.codegen", comments = "Generated by ExoCoding 0.0.1-SNAPSHOT")
@Repository
public interface OrderItemsRepository
    extends JpaRepository<OrderItems, Long>, JpaSpecificationExecutor<OrderItems> {

  void deleteByOrders(Integer orderId);

  void deleteByProducts(Integer productId);

  List<OrderItems> findByOrders(Integer orderId);

  List<OrderItems> findByProducts(Integer productId);
}
