package com.bigoviw887.modulo.filter;

import jakarta.servlet.http.HttpServletRequest;
import jakarta.servlet.http.HttpServletResponse;
import java.io.IOException;
import javax.annotation.processing.Generated;
import org.springframework.security.core.AuthenticationException;
import org.springframework.security.web.AuthenticationEntryPoint;
import org.springframework.stereotype.Component;

@Generated(value = "com.exocoding.codegen", comments = "Generated by ExoCoding 0.0.1-SNAPSHOT")
@Component
public class AuthEntryPointJwt implements AuthenticationEntryPoint {

  @Override
  public void commence(
      HttpServletRequest request,
      HttpServletResponse response,
      AuthenticationException authenticationException)
      throws IOException {

    response.setContentType("application/json");
    response.setCharacterEncoding("UTF-8");
    if (response.getStatus() == HttpServletResponse.SC_INTERNAL_SERVER_ERROR) {
      response.setStatus(HttpServletResponse.SC_UNAUTHORIZED);
    }
    response.getOutputStream();
  }
}
