
/**
 * Generated by ExoCoding 0.0.1
 */

import React from 'react';
import { useImmer } from 'use-immer';
import * as FontIcon from 'react-icons/fa';
import styles from './Sign_up.module.css';
import { updateNestedProperty } from '@/utils';
import useTitle from '@/hooks/useTitle';
import useBodystyle from '@/hooks/useBodystyle';
import { UserRegister } from '@/modules/authentication/types';
import { useNavigate } from 'react-router-dom';
import { ApiError } from '@/types';
import { signup } from '@/modules/authentication/api';
import { Row } from 'react-bootstrap';
import { Button } from 'react-bootstrap';
import { InputGroup } from 'react-bootstrap';
import { Form } from 'react-bootstrap';

type Sign_upProps = {
};

/**
 * Sign up Page
 */
export const Sign_up = (props: Sign_upProps) => {
  
        const [showPassword58445, setShowPassword58445] = React.useState<boolean>();
        const [tempUserRegister, setTempUserRegister] = useImmer<UserRegister>({} as UserRegister);

    useTitle('Signup');
    const navigate = useNavigate();

  /**
   * function to make a sign up request to the API
   */
  async function executeSignUp( ){
       const options = {
           params: {
           }
       };
await signup( tempUserRegister, options)       
setTempUserRegister ({} as UserRegister);    navigate(`/login`
        );
  }
  /**
   * function to perform the action of navigate to the login page
   */
  function goToLogin( ){
    navigate(`/login`
        );
  }
    return (
      <>

    
        <Row className={`${styles.componentIhvuNZlcVt} `} >

    
    <div className={`d-flex ${styles.componentMfKrQMyoYE} `} >

    
                <h1 className={`${styles.componentwdZZkEecOn} `}>
                    Sign Up
                </h1>
    

    
    <Form.Group className={`${styles.componentCUqiOSsNdl} `}>
            <Form.Label>
                Name
            </Form.Label>
        <InputGroup>
            <Form.Control
                type="text"
style={{backgroundColor: "", boxShadow: "", borderColor: ""}}
            value={tempUserRegister?.name}
onChange={e => setTempUserRegister(
draft => { draft.name = e.target.value; }
)}            />
        </InputGroup>
    </Form.Group>
    

    <Form.Group className={`${styles.componentCTMZWPhOHo} `}>
            <Form.Label>
                Email
            </Form.Label>
        <InputGroup style={{boxShadow: ""}}>
            <Form.Control
                type="email"
disabled={false}
style={{backgroundColor: "", borderColor: ""}}
            value={tempUserRegister?.email}
onChange={e => setTempUserRegister(
draft => { draft.email = e.target.value; }
)}            />
        </InputGroup>
    </Form.Group>

    
    <Form.Group className={`${styles.componentIPNWKpBHYh} `}>
            <Form.Label>
                Username
            </Form.Label>
        <InputGroup>
            <Form.Control
                type="text"
style={{backgroundColor: "", boxShadow: "", borderColor: ""}}
            value={tempUserRegister?.username}
onChange={e => setTempUserRegister(
draft => { draft.username = e.target.value; }
)}            />
        </InputGroup>
    </Form.Group>
    

    <Form.Group className={`${styles.componentdXtJENjIxl} `}>
            <Form.Label>
                Password
            </Form.Label>
        <InputGroup style={{boxShadow: ""}}>
            <Form.Control
                type={"showPassword58445" ? 'text' : 'password'}
style={{backgroundColor: "", borderColor: ""}}
            value={tempUserRegister?.password}
onChange={e => setTempUserRegister(
draft => { draft.password = e.target.value; }
)}            />
            <Button variant="outline-secondary" onClick={() => setShowPassword58445(!showPassword58445)}>
                {showPassword58445 ? <FontIcon.FaEyeSlash /> : <FontIcon.FaEye />}
            </Button>
        </InputGroup>
    </Form.Group>

    
        <Button
            variant="secondary"
            className={`${styles.componentNlbaPImjRM} `}
            
onClick={executeSignUp}        >
                Sign Up

        </Button>
    

    
                <a href="/login" className={`${styles.schemas_navigate} `}>
                    Already have an account? Sign in.
                </a>
    
    </div>
    
        </Row>
    
      </>
    )
};
