package com.bigoviw887.modulo.dto;

import java.util.List;
import javax.annotation.processing.Generated;
import lombok.AllArgsConstructor;
import lombok.Getter;
import lombok.NoArgsConstructor;
import lombok.Setter;

/** Object of endpoint \account */
@Generated(value = "com.exocoding.codegen", comments = "Generated by ExoCoding 0.0.1-SNAPSHOT")
@Getter
@Setter
@AllArgsConstructor
@NoArgsConstructor
public class AccountDto {

  // userObj
  protected UserObjDto user;

  // roles
  protected List<String> roles;
}
