package com.bigoviw887.modulo.dto;

import com.bigoviw887.modulo.model.TaskImportance;
import javax.annotation.processing.Generated;
import lombok.AllArgsConstructor;
import lombok.EqualsAndHashCode;
import lombok.Getter;
import lombok.NoArgsConstructor;
import lombok.Setter;

@Generated(value = "com.exocoding.codegen", comments = "Generated by ExoCoding 0.0.1-SNAPSHOT")
@Getter
@Setter
@AllArgsConstructor
@NoArgsConstructor
@EqualsAndHashCode(onlyExplicitlyIncluded = true)
public class TaskHdrDto {

  @EqualsAndHashCode.Include protected Long id;

  protected Integer tp;

  protected Integer nr;

  protected String name;

  protected TaskImportance importance;
}
