package com.bigoviw887.modulo.dto;

import javax.annotation.processing.Generated;
import lombok.AllArgsConstructor;
import lombok.Getter;
import lombok.NoArgsConstructor;
import lombok.Setter;

/** To preform the register */
@Generated(value = "com.exocoding.codegen", comments = "Generated by ExoCoding 0.0.1-SNAPSHOT")
@Getter
@Setter
@AllArgsConstructor
@NoArgsConstructor
public class UserRegisterDto {

  // username
  protected String username;

  // password
  protected String password;

  // name
  protected String name;

  // email
  protected String email;
}
