package com.bigoviw887.modulo.dto;

import javax.annotation.processing.Generated;
import lombok.AllArgsConstructor;
import lombok.EqualsAndHashCode;
import lombok.Getter;
import lombok.NoArgsConstructor;
import lombok.Setter;

/** Object of entity of User */
@Generated(value = "com.exocoding.codegen", comments = "Generated by ExoCoding 0.0.1-SNAPSHOT")
@Getter
@Setter
@AllArgsConstructor
@NoArgsConstructor
@EqualsAndHashCode(onlyExplicitlyIncluded = true)
public class UserObjDto {

  // idUser
  @EqualsAndHashCode.Include protected Long idUser;

  // name
  protected String name;

  // username
  protected String username;

  // email
  protected String email;

  // password
  protected String password;
}
