
/**
 * Generated by ExoCoding 0.0.1
 */

import React from 'react';
import { useImmer } from 'use-immer';
import * as FontIcon from 'react-icons/fa';
import styles from './Default_Layout.module.css';
import { Outlet } from 'react-router-dom';

type Default_LayoutProps = {
};

/**
 * A blank layout
 */
export const Default_Layout = (props: Default_LayoutProps) => {
  


    return (
      <>

    <Outlet />
      </>
    )
};
